export const SETTINGS_KEYS = {
    LUNCH_CUTOFF: 'LUNCH_CUTOFF_TIME',
    DINNER_CUTOFF: 'DINNER_CUTOFF_TIME',
    MEAL_RATE: 'CURRENT_MEAL_RATE',
    PREV_MEAL_RATE: 'PREVIOUS_MEAL_RATE',
    AUTO_OFF_THRESHOLD: 'AUTO_OFF_THRESHOLD',
    REPORT_DELIVERY_TIME: 'REPORT_DELIVERY_TIME',
    LAST_DELIVERY_ISO: 'LAST_DELIVERY_ISO'
};

export const DEFAULT_SETTINGS = {
    [SETTINGS_KEYS.LUNCH_CUTOFF]: '11:00',
    [SETTINGS_KEYS.DINNER_CUTOFF]: '13:00',
    [SETTINGS_KEYS.MEAL_RATE]: '70',
    [SETTINGS_KEYS.PREV_MEAL_RATE]: '70',
    [SETTINGS_KEYS.AUTO_OFF_THRESHOLD]: '-500',
    [SETTINGS_KEYS.REPORT_DELIVERY_TIME]: '10:00',
};
