export const SETTINGS_KEYS = {
    LUNCH_CUTOFF: 'LUNCH_CUTOFF_TIME',
    DINNER_CUTOFF: 'DINNER_CUTOFF_TIME',
    MEAL_RATE: 'CURRENT_MEAL_RATE',
    PREV_MEAL_RATE: 'PREVIOUS_MEAL_RATE',
    AUTO_OFF_THRESHOLD: 'AUTO_OFF_THRESHOLD'
};
